import { Customer } from "@/types";

export const INITIAL_CUSTOMERS_DATA: Customer[] = [
  {
    id: "cust_001",
    name: "Burech Mordche Oberlander",
    nameHebrew: "ברוך מרדכי אבערלענדער",
    address: "1160 Lajoie",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1N9",
    phone: "514-271-5492",
    mobile: "514-223-8210",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_002",
    name: "Shloma Oberlander",
    nameHebrew: "שלמה אבערלענדער",
    address: "704 Champagneur",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3P8",
    phone: "514-223-6862",
    mobile: "514-404-6862",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_003",
    name: "Moshe Oberlander",
    nameHebrew: "משה אבערלענדער",
    address: "Montreal",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_004",
    name: "Shloma Yitzchok Unger",
    nameHebrew: "שלמה יצחק אונגאר",
    address: "5689 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K4",
    phone: "438-503-4683",
    mobile: "438-378-6786",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_005",
    name: "Chaim Unger",
    nameHebrew: "חיים יהושע אשר אונגער",
    address: "5840 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y4",
    phone: "438-375-9711",
    mobile: "438-491-9711",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_006",
    name: "Yakov Duvid Eisdorfer",
    nameHebrew: "יעקב דוד אייזדארפער",
    address: "Montreal",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_007",
    name: "Eizen",
    nameHebrew: "יעקב אייזען",
    address: "5880 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3Y4",
    phone: "514-574-3055",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_008",
    name: "Shimon Altman",
    nameHebrew: "שמעון אלטמאן",
    address: "6062 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K8",
    phone: "514-273-8221",
    mobile: "514-830-0542",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_009",
    name: "Yoel Itzkowitz",
    nameHebrew: "יואל איצקאוויטש",
    address: "747 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S4",
    phone: "514-278-9519",
    mobile: "514-963-9519",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_010",
    name: "Shmiel Yide Itzkowitz",
    nameHebrew: "שמואל יודא איצקאוויטש",
    address: "181 De L'epee",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3T1",
    phone: "514-270-4097",
    mobile: "438-404-3165",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_011",
    name: "Yakov Hersh Appeldorfer",
    nameHebrew: "יעקב הערש אפעלדארפער",
    address: "780 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3W9",
    phone: "514-279-1967",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_012",
    name: "Cheskel Appel",
    nameHebrew: "יחזקאל שרגא אפפעל",
    address: "663 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S2",
    mobile: "917-748-0764",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_013",
    name: "Yoel Ackerman",
    nameHebrew: "יואל אקערמאן",
    address: "304 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3W3",
    phone: "514-272-6294",
    mobile: "438-764-6299",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_014",
    name: "Yisroel Ackerman",
    nameHebrew: "ישראל אקערמאן",
    address: "6096 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1X6",
    phone: "514-274-2032",
    mobile: "263-993-2399",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_015",
    name: "Mordechai Orgel",
    nameHebrew: "מרדכי ארגעל",
    address: "5192 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3X8",
    mobile: "450-949-0055",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_016",
    name: "Rabbi Chaim Ashkenazi",
    nameHebrew: "הרב חיים אשכנזי שליט\"א",
    address: "149 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3V8",
    phone: "514-313-6563",
    mobile: "438-878-6563",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_017",
    name: "Arye Buchinger",
    nameHebrew: "ארי' בוכינגער",
    address: "633 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S2",
    phone: "514-276-9932",
    mobile: "438-995-7968",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_018",
    name: "Yakov Bikel",
    nameHebrew: "יעקב ביקעל",
    address: "5641 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B5",
    phone: "514-495-6545",
    mobile: "514-992-9077",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_019",
    name: "Lipa Blumentahl",
    nameHebrew: "ליפא בלומענטאל",
    address: "5379 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3X9",
    phone: "514-271-4097",
    mobile: "514-738-2700",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_020",
    name: "Mordechai Blumentahl",
    nameHebrew: "מרדכי בלומענטאל",
    address: "6056 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V 4C2",
    mobile: "845-662-3000",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_021",
    name: "Yisrul Blier",
    nameHebrew: "ישראל בלייער",
    address: "5686 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y2",
    phone: "514-274-1973",
    mobile: "514-568-7998",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_022",
    name: "Yoel Berger",
    nameHebrew: "יואל ברי\"ט בערגער",
    address: "760 De L'epee",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3T9",
    mobile: "845-502-1616",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_023",
    name: "Yoel Berger",
    nameHebrew: "יואל בערגער",
    address: "6128 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K8",
    phone: "514-272-2363",
    mobile: "514-250-2363",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_024",
    name: "Yisruel Moshe Brody",
    nameHebrew: "ישראל משה בראדי",
    address: "5239 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B4",
    phone: "514-279-5856",
    mobile: "514-830-6405",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_025",
    name: "Shlome Yide Broder",
    nameHebrew: "שלמה יודא בראדער",
    address: "6071 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y7",
    phone: "514-224-1341",
    mobile: "438-389-5078",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_026",
    name: "Elimilech Brach",
    nameHebrew: "אלימלך בראך",
    address: "1371 Lajoie",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1P6",
    phone: "514-495-4056",
    mobile: "514-963-4056",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_027",
    name: "Eliazer Leib Brach",
    nameHebrew: "אליעזר לייב בראך",
    address: "21 Duverger",
    city: "Montreal",
    state: "QC",
    zip: "H2V 1M9",
    mobile: "646-864-6854",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_028",
    name: "Pinchus Brach",
    nameHebrew: "פנחס בראך",
    address: "5724 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B6",
    phone: "514-277-1522",
    mobile: "514-691-4862",
    createdAt: new Date().toISOString()
  }
];