import { Customer } from "@/types";

export const INITIAL_CUSTOMERS_DATA: Customer[] = [
  {
    id: "cust_001",
    name: "Burech Mordche Oberlander",
    nameHebrew: "ברוך מרדכי אבערלענדער",
    address: "1160 Lajoie",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1N9",
    phone: "514-271-5492",
    mobile: "514-223-8210",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_002",
    name: "Shloma Oberlander",
    nameHebrew: "שלמה אבערלענדער",
    address: "704 Champagneur",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3P8",
    phone: "514-223-6862",
    mobile: "514-404-6862",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_003",
    name: "Moshe Oberlander",
    nameHebrew: "משה אבערלענדער",
    address: "Montreal",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_004",
    name: "Shloma Yitzchok Unger",
    nameHebrew: "שלמה יצחק אונגאר",
    address: "5689 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K4",
    phone: "438-503-4683",
    mobile: "438-378-6786",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_005",
    name: "Chaim Unger",
    nameHebrew: "חיים יהושע אשר אונגער",
    address: "5840 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y4",
    phone: "438-375-9711",
    mobile: "438-491-9711",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_006",
    name: "Yakov Duvid Eisdorfer",
    nameHebrew: "יעקב דוד אייזדארפער",
    address: "Montreal",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_007",
    name: "Eizen",
    nameHebrew: "יעקב אייזען",
    address: "5880 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3Y4",
    phone: "514-574-3055",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_008",
    name: "Shimon Altman",
    nameHebrew: "שמעון אלטמאן",
    address: "6062 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K8",
    phone: "514-273-8221",
    mobile: "514-830-0542",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_009",
    name: "Yoel Itzkowitz",
    nameHebrew: "יואל איצקאוויטש",
    address: "747 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S4",
    phone: "514-278-9519",
    mobile: "514-963-9519",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_010",
    name: "Shmiel Yide Itzkowitz",
    nameHebrew: "שמואל יודא איצקאוויטש",
    address: "181 De L'epee",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3T1",
    phone: "514-270-4097",
    mobile: "438-404-3165",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_011",
    name: "Yakov Hersh Appeldorfer",
    nameHebrew: "יעקב הערש אפעלדארפער",
    address: "780 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3W9",
    phone: "514-279-1967",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_012",
    name: "Cheskel Appel",
    nameHebrew: "יחזקאל שרגא אפפעל",
    address: "663 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S2",
    mobile: "917-748-0764",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_013",
    name: "Yoel Ackerman",
    nameHebrew: "יואל אקערמאן",
    address: "304 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3W3",
    phone: "514-272-6294",
    mobile: "438-764-6299",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_014",
    name: "Yisroel Ackerman",
    nameHebrew: "ישראל אקערמאן",
    address: "6096 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1X6",
    phone: "514-274-2032",
    mobile: "263-993-2399",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_015",
    name: "Mordechai Orgel",
    nameHebrew: "מרדכי ארגעל",
    address: "5192 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3X8",
    mobile: "450-949-0055",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_016",
    name: "Rabbi Chaim Ashkenazi",
    nameHebrew: "הרב חיים אשכנזי שליט\"א",
    address: "149 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3V8",
    phone: "514-313-6563",
    mobile: "438-878-6563",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_017",
    name: "Arye Buchinger",
    nameHebrew: "ארי' בוכינגער",
    address: "633 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S2",
    phone: "514-276-9932",
    mobile: "438-995-7968",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_018",
    name: "Yakov Bikel",
    nameHebrew: "יעקב ביקעל",
    address: "5641 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B5",
    phone: "514-495-6545",
    mobile: "514-992-9077",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_019",
    name: "Lipa Blumentahl",
    nameHebrew: "ליפא בלומענטאל",
    address: "5379 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3X9",
    phone: "514-271-4097",
    mobile: "514-738-2700",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_020",
    name: "Mordechai Blumentahl",
    nameHebrew: "מרדכי בלומענטאל",
    address: "6056 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V 4C2",
    mobile: "845-662-3000",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_021",
    name: "Yisrul Blier",
    nameHebrew: "ישראל בלייער",
    address: "5686 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y2",
    phone: "514-274-1973",
    mobile: "514-568-7998",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_022",
    name: "Yoel Berger",
    nameHebrew: "יואל ברי\"ט בערגער",
    address: "760 De L'epee",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3T9",
    mobile: "845-502-1616",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_023",
    name: "Yoel Berger",
    nameHebrew: "יואל בערגער",
    address: "6128 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K8",
    phone: "514-272-2363",
    mobile: "514-250-2363",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_024",
    name: "Yisruel Moshe Brody",
    nameHebrew: "ישראל משה בראדי",
    address: "5239 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B4",
    phone: "514-279-5856",
    mobile: "514-830-6405",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_025",
    name: "Shlome Yide Broder",
    nameHebrew: "שלמה יודא בראדער",
    address: "6071 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y7",
    phone: "514-224-1341",
    mobile: "438-389-5078",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_026",
    name: "Elimilech Brach",
    nameHebrew: "אלימלך בראך",
    address: "1371 Lajoie",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1P6",
    phone: "514-495-4056",
    mobile: "514-963-4056",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_027",
    name: "Eliazer Leib Brach",
    nameHebrew: "אליעזר לייב בראך",
    address: "21 Duverger",
    city: "Montreal",
    state: "QC",
    zip: "H2V 1M9",
    mobile: "646-864-6854",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_028",
    name: "Pinchus Brach",
    nameHebrew: "פנחס בראך",
    address: "5724 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B6",
    phone: "514-277-1522",
    mobile: "514-691-4862",
    createdAt: new Date().toISOString()
  },
  // Page 2
  {
    id: "cust_029",
    name: "Yisrul Brief",
    nameHebrew: "ישראל בריעף",
    address: "5714 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y2",
    mobile: "438-365-1595",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_030",
    name: "Hershel Goldberger",
    nameHebrew: "בנציון צבי גאלדבערגער",
    address: "25 Laviolette",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1X6",
    phone: "514-271-5651",
    mobile: "514-806-5651",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_031",
    name: "Yoel Goldberger",
    nameHebrew: "יואל גאלדבערגער",
    address: "5850 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4C1",
    phone: "514-272-4598",
    mobile: "514-586-4598",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_032",
    name: "Mordche Arye Goldberger",
    nameHebrew: "מרדכי ארי' גאלדבערגער",
    address: "5432 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B3",
    phone: "514-274-5245",
    mobile: "438-994-4599",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_033",
    name: "Mendel Goldberger",
    nameHebrew: "מנחם מענדל גאלדבערגער",
    address: "5847 Parc",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4H4",
    mobile: "438-764-2268",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_034",
    name: "Shimon Goldberger",
    nameHebrew: "שמעון גאלדבערגער",
    address: "5281 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K3",
    phone: "514-276-7926",
    mobile: "438-630-7296",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_035",
    name: "Yoel Goldman",
    nameHebrew: "יואל גאלדמאן",
    address: "5967 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y5",
    phone: "514-272-0060",
    mobile: "438-938-8409",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_036",
    name: "Mordche Hersh Goldman",
    nameHebrew: "מרדכי הערש גאלדמאן",
    address: "6069 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B7",
    phone: "514-274-9027",
    mobile: "514-913-9027",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_037",
    name: "Duvid Goldstein",
    nameHebrew: "דוד גאלדשטיין",
    address: "480 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3R8",
    mobile: "845-395-8185",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_038",
    name: "Yisruel Shulem Gandel",
    nameHebrew: "ישראל שלום גאנدل",
    address: "656 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3W8",
    phone: "514-903-7776",
    mobile: "438-509-5261",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_039",
    name: "Chaim Yakov Guttman",
    nameHebrew: "חיים יעקב גוטטמאן",
    address: "867 McEachren",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3C9",
    phone: "514-992-5090",
    mobile: "438-878-8352",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_040",
    name: "Yossef Guttman",
    nameHebrew: "יוסף גוטטמאן",
    address: "1248 Lajoie",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1P1",
    phone: "514-277-3768",
    mobile: "438-398-8412",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_041",
    name: "Menachem Mandel Guttman",
    nameHebrew: "מנחם מע德尔 גוטטמאן",
    address: "687 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S2",
    phone: "514-313-1034",
    mobile: "438-876-7616",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_042",
    name: "Pinchus Glauber",
    nameHebrew: "פנחס גלויבער",
    address: "735 A Champagneur",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3P9",
    phone: "514-272-2063",
    mobile: "438-938-9136",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_043",
    name: "Hersh Elimeilech Glick",
    nameHebrew: "הערש אלימלך גליק",
    address: "5342 Esplanade",
    city: "Montreal",
    state: "QC",
    zip: "H2T-2Z7",
    phone: "514-495-8642",
    mobile: "514-885-8640",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_044",
    name: "Akive Peisech Glick",
    nameHebrew: "עקיבא פסח גליק",
    address: "709 Champagneur",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3P9",
    phone: "514-271-0542",
    mobile: "514-452-4175",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_045",
    name: "Yida Moshe Gelb",
    nameHebrew: "יודא משה געלב",
    address: "358 De L'epee",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3T6",
    phone: "514-277-0388",
    mobile: "514-531-3504",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_046",
    name: "Moshe Eliezer Gestetner",
    nameHebrew: "משה אליעזר געויטנער",
    address: "5252 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V 4K4",
    mobile: "514-358-6428",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_047",
    name: "Berish Gross",
    nameHebrew: "בעريس גראס",
    address: "5269 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B4",
    phone: "514-276-9312",
    mobile: "514-993-5273",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_048",
    name: "Yidel Gross",
    nameHebrew: "יקותיאל יודא צבי גראס",
    address: "780 B Champagneur",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3P8",
    mobile: "845-772-5490",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_049",
    name: "Mordche Gross",
    nameHebrew: "מרדכי גראס",
    address: "5714 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B6",
    phone: "514-270-6668",
    mobile: "514-963-6668",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_050",
    name: "Mrs Shmiel Gruber",
    nameHebrew: "מרת שמואל גרובער",
    address: "5462 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V 4B3",
    phone: "514-467-2784",
    mobile: "514-463-7287",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_051",
    name: "Yoel Yeshea Green",
    nameHebrew: "יואל יושע גרין",
    address: "737 A De L'epee",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3V1",
    phone: "514-240-4008",
    mobile: "514-880-6731",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_052",
    name: "Shaul Chezkel Greenfeld",
    nameHebrew: "שאול יחזקאל גרינפלד",
    address: "5581 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V 4B5",
    phone: "514-885-7311",
    mobile: "514-424-7311",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_053",
    name: "Nusen Binyomin Grintzweig",
    nameHebrew: "נתן בנימין גרינצווייג",
    address: "1044 St. Viateur",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1Y3",
    mobile: "514-550-5329",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_054",
    name: "Mordchai Danziger",
    nameHebrew: "מרדכי דאנליטער",
    address: "5839 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3Y5",
    phone: "514-276-2942",
    mobile: "438-876-6942",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_055",
    name: "Yoel Shaye Deutch",
    nameHebrew: "יואל ישעי' דייטש",
    address: "5459 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3X9",
    phone: "514-273-1773",
    mobile: "514-815-6876",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_056",
    name: "Avrum Yosef Drummer",
    nameHebrew: "אברהם יוסף דרוממער",
    address: "5781 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y3",
    phone: "514-272-0342",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_057",
    name: "Chaim Drezner",
    nameHebrew: "חיים דרעזנער",
    address: "1140 Lajoie",
    city: "Montreal",
    state: "QC",
    zip: "H2V 1N8",
    phone: "514-979-8642",
    mobile: "438-506-6345",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_058",
    name: "Yoel Drezner",
    nameHebrew: "יואל דרעזנער",
    address: "6032 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y6",
    phone: "514-272-0928",
    mobile: "514-867-7389",
    createdAt: new Date().toISOString()
  },
  // Page 3
  {
    id: "cust_059",
    name: "Shlome Horowitz",
    nameHebrew: "שלמה הורוויץ",
    address: "1044 Van Horne",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_060",
    name: "Sender Heimlich",
    nameHebrew: "אלכסנדר יושע היימליך",
    address: "6068 Hutchison",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_061",
    name: "Yakov Yechesky Heimlich",
    nameHebrew: "יעקב יחזקי'היימליך",
    address: "5867 Hutchison",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_062",
    name: "Rabbi Hirchfeld",
    nameHebrew: "הרב חיים אלעזר הירשפעלד שליט\"א",
    address: "735 A Outremont",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_063",
    name: "Elya Hersko",
    nameHebrew: "אלי' הערשקא",
    address: "675 Bloomfield",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_064",
    name: "Yisruel Hershkowitz",
    nameHebrew: "ישראל הערשקאוויימש",
    address: "497 Querbes",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_065",
    name: "Usher Wieder",
    nameHebrew: "אשר וויעדער",
    address: "5150 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_066",
    name: "Joseph Wieder",
    nameHebrew: "יוסף יושע ווידער",
    address: "5448 Hutchison",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_067",
    name: "Menachem Gershon Wieder",
    nameHebrew: "מנחם גרשון ווידער",
    address: "666 Outremont",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_068",
    name: "Lazer Weiser",
    nameHebrew: "אליעזר ווייזער",
    address: "737 Outremont",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_069",
    name: "Berish Weiser",
    nameHebrew: "בעריש ווייזער",
    address: "832 Bloomfield",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_070",
    name: "Shlomo hersh Weiser",
    nameHebrew: "שלמה צבי ווייזער",
    address: "1045 St. Viateur",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_071",
    name: "Avigdor duniel Weinberger",
    nameHebrew: "אביגדור דניאל וויינבערגער",
    address: "696 De L'epee",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_072",
    name: "Joel Weinberger",
    nameHebrew: "יואל וויינבערגער",
    address: "164 Querbes",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_073",
    name: "Nesanel Weinberger",
    nameHebrew: "נתנאל וויינבערגער",
    address: "661 Querbes",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_074",
    name: "Shmiel Weinberger",
    nameHebrew: "שמואל וויינבערגער",
    address: "6192 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_075",
    name: "Simcha Yisroel moshe Weinberger",
    nameHebrew: "שמחה ישראל משה וויינבערגער",
    address: "642 Bloomfield",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_076",
    name: "Gimpl Weingarten",
    nameHebrew: "מרדכי גימפל וויינגארט",
    address: "5983 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_077",
    name: "Aron Weiss",
    nameHebrew: "אהרן ווייס",
    address: "453 Querbes",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_078",
    name: "Cheim Yceskel Weiss",
    nameHebrew: "חיים יחזקאל ווייס",
    address: "753 Querbes",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_079",
    name: "Yidel Weiss",
    nameHebrew: "יודא ווייס",
    address: "5676 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_080",
    name: "Yosef Leib Weiss",
    nameHebrew: "יוסף לייב ווייס",
    address: "5860 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_081",
    name: "Yikiseil Hersh Weiss",
    nameHebrew: "יקותיאל הערש ווייס",
    address: "168 Querbes",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_082",
    name: "Menachem Weiss",
    nameHebrew: "מנחם ווייס",
    address: "5520 Hutchison",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_083",
    name: "Moshe Weiss",
    nameHebrew: "משה ווייס",
    address: "1328 Lajoie",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_084",
    name: "Kalmen Weiss",
    nameHebrew: "קלמן ווייס",
    address: "5672 Hutchison",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_085",
    name: "Simon Weiss",
    nameHebrew: "שמעון ווייס",
    address: "1042 Van Horne",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_086",
    name: "Samson Weiss",
    nameHebrew: "שמשון ווייס",
    address: "6056 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_087",
    name: "Gershon Weissman",
    nameHebrew: "גרשון ווייסמאן",
    address: "5606 Esplanade",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_088",
    name: "Isaac Weberman",
    nameHebrew: "יצחק אייזיק וועבערמאן",
    address: "1130 Fairmount",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_089",
    name: "Mordche Weberman",
    nameHebrew: "מרדכי וועבערמאן",
    address: "5178 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  // Page 4
  {
    id: "cust_090",
    name: "Yoel Wechter",
    nameHebrew: "יואל וועכטער",
    address: "740 A De L'epee",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_091",
    name: "Akive Weltz",
    nameHebrew: "עקיבא שמואל וועלץ",
    address: "160 Querbes",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_092",
    name: "Berl Wertheimer",
    nameHebrew: "בערל ווערטהיימער",
    address: "780 Querbes",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_093",
    name: "Burech Mordche Wertheimer",
    nameHebrew: "ברוך מרדכי ווערטהיימער",
    address: "733 A De L'epee",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_094",
    name: "Shabshe Wertheimer",
    nameHebrew: "שבתי ווערטהיימער",
    address: "19 Laviolette",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_095",
    name: "Avrum Duvid Wertzberger",
    nameHebrew: "אברהם דוד ווערצבערגער",
    address: "551 Champagneur",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_096",
    name: "Avrum Meir Wertzberger",
    nameHebrew: "אברהם מאיר ווערצבערגער",
    address: "5235 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_097",
    name: "Chaim shulem Wertzberger",
    nameHebrew: "חיים שלום ווערצבערגער",
    address: "5935 Hutchison",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_098",
    name: "Mrs Wertzberger",
    nameHebrew: "מרת יושע ווערצבערגער",
    address: "561 Querbes",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_099",
    name: "Rabbi Mendel Wertzberger",
    nameHebrew: "הרב מענדל ווערצבערגער שליט\"א דומ\"ץ",
    address: "5595 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_100",
    name: "Moshe Wertzberger",
    nameHebrew: "משה ווערצבערגער",
    address: "5864 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_101",
    name: "Moshe Chaim Wertzberger",
    nameHebrew: "משה חיים ווערצבערגער",
    address: "5422 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_102",
    name: "Moshe Yeshaya Wertzberger",
    nameHebrew: "משה ישעי' ווערצבערגער",
    address: "5789 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_103",
    name: "shlome Wertzberger",
    nameHebrew: "שלמה ווערצבערגער",
    address: "6184 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_104",
    name: "Moshe Eliezer Zolden",
    nameHebrew: "משה אליעזר זאלדאן",
    address: "5936 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_105",
    name: "Moshe Zilber",
    nameHebrew: "משה שמשון זילבער",
    address: "1033 #4 Van Horne",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_106",
    name: "Arye Leib Silberstein",
    nameHebrew: "ארי' לייב זילבערשטיין",
    address: "682 De L'epee",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_107",
    name: "Burich Zeltzer",
    nameHebrew: "ברוך זעלצער",
    address: "460 Champagneur",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_108",
    name: "Chaim Nuchem Tauber",
    nameHebrew: "חיים נחום טויבער",
    address: "550 Outremont",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_109",
    name: "Rabbi Gavriel Yide Teitelbom",
    nameHebrew: "הרב גבריאל יודא טייטלבוים שליט\"א",
    address: "645 De L'epee",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_110",
    name: "Alter Yakev Tyrnauer",
    nameHebrew: "אלטר יעקב טירנויער",
    address: "5972 Hutchison",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_111",
    name: "Yoel Teller",
    nameHebrew: "יואל טעללער",
    address: "713 Bloomfield",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_112",
    name: "moshe Teller",
    nameHebrew: "משה טעללער",
    address: "1130 Fairmount",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_113",
    name: "Aharon Ozer Tessler",
    nameHebrew: "אהרן עוזר טעסלער",
    address: "Montreal",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_114",
    name: "Mordche Shabsi Yakobowitz",
    nameHebrew: "מרדכי שבתי יעקappaוויטש",
    address: "149 De L'epee",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_115",
    name: "Abraham Ely Katz",
    nameHebrew: "אברהם אלי' כ\"ץ",
    address: "745 De L'epee",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_116",
    name: "Yoel Katz",
    nameHebrew: "יואל כ\"ץ",
    address: "545 Champagneur",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_117",
    name: "Moshe Hersh Katz",
    nameHebrew: "משה הערש כ\"ץ",
    address: "5960 Hutchison",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_118",
    name: "Chaim Katz",
    nameHebrew: "חיים כ\"ץ",
    address: "6110 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_119",
    name: "Shimon Yisrul Kahana",
    nameHebrew: "שמעון ישראל כהנא",
    address: "5270 Durocher",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_120",
    name: "Mair Naftula Lazer",
    nameHebrew: "מאיר נפתלי לאזאר",
    address: "5460 Hutchison",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  // Page 5
  { id: "cust_121", name: "Yoel Meir Landau", nameHebrew: "יואל מאיר לאנדא", address: "6190 Durocher", city: "Montreal", state: "QC", phone: "438-383-4545", mobile: "514-516-5120", createdAt: new Date().toISOString() },
  { id: "cust_122", name: "Cheskel Landau", nameHebrew: "יחזקאל שרגא לאנדא", address: "1130 Fairmount", city: "Montreal", state: "QC", mobile: "438-406-3017", createdAt: new Date().toISOString() },
  { id: "cust_123", name: "Moshe Landau", nameHebrew: "משה לאנדא", address: "789 A Champagneur", city: "Montreal", state: "QC", phone: "514-809-2178", mobile: "438-409-2179", createdAt: new Date().toISOString() },
  { id: "cust_124", name: "Moshe Shmiel Landau", nameHebrew: "משה שמואל לאנדא", address: "5954 Durocher", city: "Montreal", state: "QC", phone: "514-276-6752", mobile: "438-876-6752", createdAt: new Date().toISOString() },
  { id: "cust_125", name: "Avrom Sholem Listigman", nameHebrew: "אברהם שלום לוסטיגמאן", address: "1210 Lajoie", city: "Montreal", state: "QC", mobile: "514-781-4056", createdAt: new Date().toISOString() },
  { id: "cust_126", name: "Shmelka Lichtman", nameHebrew: "שמואל שמעלקא ליכטמאן", address: "5464 Hutchison", city: "Montreal", state: "QC", phone: "514-273-8785", mobile: "514-608-4058", createdAt: new Date().toISOString() },
  { id: "cust_127", name: "Yoel Lebowitz", nameHebrew: "יואל לעבאוויטש", address: "6022 Hutchison", city: "Montreal", state: "QC", phone: "514-227-1309", mobile: "514-815-9309", createdAt: new Date().toISOString() },
  { id: "cust_128", name: "Hilel Lowy", nameHebrew: "הלל לעווי", address: "5463 Hutchison", city: "Montreal", state: "QC", phone: "514-419-1922", mobile: "438-509-4901", createdAt: new Date().toISOString() },
  { id: "cust_129", name: "Leibish Lowy", nameHebrew: "לייבוש לעווי", address: "1204 Lajoie", city: "Montreal", state: "QC", phone: "514-379-6345", mobile: "438-876-6345", createdAt: new Date().toISOString() },
  { id: "cust_130", name: "Mayer Nissan Lowy", nameHebrew: "מאיר ניסן לעווי", address: "5576 Durocher", city: "Montreal", state: "QC", phone: "514-274-7366", mobile: "438-931-7366", createdAt: new Date().toISOString() },
  { id: "cust_131", name: "Kalmen Eliezer Lowy", nameHebrew: "קלמן אליעזר לעווי", address: "5674 Jeanne Mance", city: "Montreal", state: "QC", phone: "514-273-6315", mobile: "514-915-6315", createdAt: new Date().toISOString() },
  { id: "cust_132", name: "Shmiel Malik", nameHebrew: "שמואל מאליק", address: "5991 Hutchison", city: "Montreal", state: "QC", mobile: "438-827-6848", createdAt: new Date().toISOString() },
  { id: "cust_133", name: "Mechl Moskowitz", nameHebrew: "יחיאל מיכל מאסקאוויטש", address: "5860 Jeanne Mance", city: "Montreal", state: "QC", phone: "514-495-9150", mobile: "514-608-4058", createdAt: new Date().toISOString() },
  { id: "cust_134", name: "Yakev Moravke", nameHebrew: "יצחק יעקב מאראווקע", address: "482 Wiseman", city: "Montreal", state: "QC", phone: "514-271-2786", mobile: "514-378-5550", createdAt: new Date().toISOString() },
  { id: "cust_135", name: "Avrom Yitzchok Markowitz", nameHebrew: "אברהם יצחק מארקאוויטש", address: "1072 St. Viateur", city: "Montreal", state: "QC", phone: "514-807-5020", mobile: "514-294-7097", createdAt: new Date().toISOString() },
  { id: "cust_136", name: "Wolf Markowitz", nameHebrew: "בנימין זאב מארקאוויטש", address: "5534 Hutchison", city: "Montreal", state: "QC", phone: "514-225-5423", mobile: "514-557-0211", createdAt: new Date().toISOString() },
  { id: "cust_137", name: "Yoel Shulem Markowitz", nameHebrew: "יואל שלום מארקאוויטש", address: "567 Outremont", city: "Montreal", state: "QC", phone: "514-278-1518", mobile: "514-224-7424", createdAt: new Date().toISOString() },
  { id: "cust_138", name: "Yosef Yide Markowitz", nameHebrew: "יוסף יודא מארקאוויטש", address: "5650 Hutchison", city: "Montreal", state: "QC", phone: "514-274-8149", mobile: "514-654-3851", createdAt: new Date().toISOString() },
  { id: "cust_139", name: "Yisreal Shulem Markowitz", nameHebrew: "ישראל שלום מארקאוויטש", address: "1208 Lajoie", city: "Montreal", state: "QC", phone: "514-903-3934", mobile: "438-934-3934", createdAt: new Date().toISOString() },
  { id: "cust_140", name: "Mrs Moskowitz", nameHebrew: "יצחק יעקב מאשקאוויטש", address: "745 A Querbes", city: "Montreal", state: "QC", phone: "514-270-5463", createdAt: new Date().toISOString() },
  { id: "cust_141", name: "Moshe Zev Moskowitz", nameHebrew: "משה זאב מאשקאוויטש", address: "531 A Champagneur", city: "Montreal", state: "QC", mobile: "438-529-3561", createdAt: new Date().toISOString() },
  { id: "cust_142", name: "Yoel Mittleman", nameHebrew: "יואל מיטטעלמאן", address: "5310 Durocher", city: "Montreal", state: "QC", phone: "514-948-6090", mobile: "514-606-6090", createdAt: new Date().toISOString() },
  { id: "cust_143", name: "Yoel Mittleman", nameHebrew: "יואל מיטטעלמאן", address: "661 Querbes", city: "Montreal", state: "QC", phone: "514-495-7963", mobile: "514-715-7963", createdAt: new Date().toISOString() },
  { id: "cust_144", name: "D. Meizlish", nameHebrew: "אב\"ד", address: "5311 Durocher", city: "Montreal", state: "QC", phone: "514-495-2731", mobile: "214-230-0391", createdAt: new Date().toISOString() },
  { id: "cust_145", name: "Shimon Zev Meizlish", nameHebrew: "שמעון זאב מייזליש", address: "733 B De L'epee", city: "Montreal", state: "QC", phone: "514-315-4951", mobile: "438-764-2139", createdAt: new Date().toISOString() },
  { id: "cust_146", name: "Moshe Chaim Mayer", nameHebrew: "משה חיים אשר מייער", address: "5291 Durocher", city: "Montreal", state: "QC", phone: "514-279-8967", mobile: "514-898-8967", createdAt: new Date().toISOString() },
  { id: "cust_147", name: "Shia Yizchok Miler", nameHebrew: "יושע יצחק מיללער", address: "1152 St. Viateur", city: "Montreal", state: "QC", phone: "514-903-8677", mobile: "438-938-0613", createdAt: new Date().toISOString() },
  { id: "cust_148", name: "Yonoson Binyumin Mezay", nameHebrew: "יונתן בנימין מעזעי", address: "5245 Hutchison", city: "Montreal", state: "QC", mobile: "514-779-4097", createdAt: new Date().toISOString() },
  { id: "cust_149", name: "Yosef Mordche Mermelstein", nameHebrew: "יוסף מרדכי מערמעלשטיין", address: "669 Querbes", city: "Montreal", state: "QC", phone: "514-223-7884", mobile: "514-970-7884", createdAt: new Date().toISOString() },
  { id: "cust_150", name: "Elimeilech Mertz", nameHebrew: "אלימלך מערץ", address: "5905 Hutchison", city: "Montreal", state: "QC", mobile: "514-462-3329", createdAt: new Date().toISOString() },
  { id: "cust_151", name: "Yisruel Zev Mertz", nameHebrew: "ישראל זאב מערץ", address: "786 A Champagneur", city: "Montreal", state: "QC", phone: "438-680-2853", mobile: "438-509-3256", createdAt: new Date().toISOString() },
  // Page 6
  { id: "cust_152", name: "Shimon Mertz", nameHebrew: "שמעון מערץ", address: "5243 Hutchison", city: "Montreal", state: "QC", phone: "514-507-2221", mobile: "438-389-6387", createdAt: new Date().toISOString() },
  { id: "cust_153", name: "Efriam Zalman Marguliyes", nameHebrew: "אפרים זלמן מרגליות", address: "6119 Hutchison", city: "Montreal", state: "QC", phone: "514-278-8510", mobile: "438-764-8511", createdAt: new Date().toISOString() },
  { id: "cust_154", name: "Shmiel Neihauser", nameHebrew: "שמואל לוי נייבויזער", address: "1336 Lajoie", city: "Montreal", state: "QC", phone: "514-944-4893", mobile: "438-530-3281", createdAt: new Date().toISOString() },
  { id: "cust_155", name: "Asher Lemel Neuman", nameHebrew: "אשר לעמל ניימאן", address: "708 Outremont", city: "Montreal", state: "QC", mobile: "438-883-6413", createdAt: new Date().toISOString() },
  { id: "cust_156", name: "Yisruel Neuman", nameHebrew: "ישראל ניימאן", address: "700 B Champagneur", city: "Montreal", state: "QC", mobile: "514-269-0169", createdAt: new Date().toISOString() },
  { id: "cust_157", name: "Avigdor Meir Samet", nameHebrew: "אביגדור מאיר סאמעט", address: "742 Querbes", city: "Montreal", state: "QC", phone: "514-271-6358", mobile: "438-401-9725", createdAt: new Date().toISOString() },
  { id: "cust_158", name: "Wolf Samet", nameHebrew: "וואלף סאמעט", address: "725 Outremont", city: "Montreal", state: "QC", phone: "514-834-7497", mobile: "438-530-7497", createdAt: new Date().toISOString() },
  { id: "cust_159", name: "yoel Samet", nameHebrew: "יואל סאמעט", address: "5409 Jeanne Mance", city: "Montreal", state: "QC", phone: "514-279-9572", mobile: "514-583-1217", createdAt: new Date().toISOString() },
  { id: "cust_160", name: "Yisruel Avigdor Samet", nameHebrew: "ישראל אביגדור סאמעט", address: "5359 Jeanne Mance", city: "Montreal", state: "QC", phone: "514-272-6338", createdAt: new Date().toISOString() },
  { id: "cust_161", name: "Joel Sofer", nameHebrew: "יואל סופר", address: "711 Bloomfield", city: "Montreal", state: "QC", phone: "514-278-4097", mobile: "438-406-4097", createdAt: new Date().toISOString() },
  { id: "cust_162", name: "Avrum Chaim Strulowitz", nameHebrew: "אברהם חיים סטרולאוויטש", address: "1044 St. Viateur", city: "Montreal", state: "QC", phone: "514-274-7366", mobile: "438-506-9858", createdAt: new Date().toISOString() },
  { id: "cust_163", name: "Nuchem Samson Ostreicher", nameHebrew: "נחום שמשון עסטרייכער", address: "470 Wiseman", city: "Montreal", state: "QC", phone: "514-272-4214", createdAt: new Date().toISOString() },
  { id: "cust_164", name: "Lipa Epstein", nameHebrew: "ליפא עפשטיין", address: "5708 Jeanne Mance", city: "Montreal", state: "QC", phone: "514-277-2673", mobile: "514-223-8709", createdAt: new Date().toISOString() },
  { id: "cust_165", name: "Yisroel Ekstein", nameHebrew: "ישראל עקשטיין", address: "6066 Hutchison", city: "Montreal", state: "QC", phone: "514-270-3773", mobile: "514-261-2869", createdAt: new Date().toISOString() },
  { id: "cust_166", name: "Nusen Binumin Ekstein", nameHebrew: "נתן בנימין עקשטיין", address: "5925 Durocher", city: "Montreal", state: "QC", phone: "514-276-5534", mobile: "438-932-5534", createdAt: new Date().toISOString() },
  { id: "cust_167", name: "Elimeilich Fogel", nameHebrew: "אלימלך פאגעל", address: "5158 Durocher", city: "Montreal", state: "QC", phone: "514-272-2796", createdAt: new Date().toISOString() },
  { id: "cust_168", name: "Toivye Fogel", nameHebrew: "טובי' פאגעל", address: "666 Bloomfield", city: "Montreal", state: "QC", phone: "514-569-6752", mobile: "438-506-9737", createdAt: new Date().toISOString() },
  { id: "cust_169", name: "Moshe Fogel", nameHebrew: "משה פאגעל", address: "6147 Durocher", city: "Montreal", state: "QC", phone: "514-279-0555", mobile: "438-763-5486", createdAt: new Date().toISOString() },
  { id: "cust_170", name: "Yakev Shia Polacheck", nameHebrew: "יעקב יושע פאלאטשעק", address: "6186 Durocher", city: "Montreal", state: "QC", phone: "514-632-9312", mobile: "514-963-4668", createdAt: new Date().toISOString() },
  { id: "cust_171", name: "Shia Follman", nameHebrew: "יושע פאללמאן", address: "5629 Hutchison", city: "Montreal", state: "QC", phone: "514-279-1558", mobile: "438-764-1558", createdAt: new Date().toISOString() },
  { id: "cust_172", name: "Shlome Folkowitz", nameHebrew: "שלמה פאלקאוויטש", address: "731 A De L'epee", city: "Montreal", state: "QC", mobile: "438-509-1305", createdAt: new Date().toISOString() },
  { id: "cust_173", name: "Shlome Porges", nameHebrew: "שלמה פארגעס", address: "609 Querbes", city: "Montreal", state: "QC", phone: "514-543-8221", mobile: "438-498-1580", createdAt: new Date().toISOString() },
  { id: "cust_174", name: "Burech Mordcha Fischer", nameHebrew: "ברוך מרדכי פישער", address: "6049 Parc Ave.", city: "Montreal", state: "QC", mobile: "514-663-7761", createdAt: new Date().toISOString() },
  { id: "cust_175", name: "Yoel Usher Fischer", nameHebrew: "יואל אשר פישער", address: "5639 Durocher", city: "Montreal", state: "QC", phone: "514-495-0804", mobile: "514-913-0804", createdAt: new Date().toISOString() },
  { id: "cust_176", name: "Yoel Fleishman", nameHebrew: "יואל פליישמאן", address: "779 Outremont", city: "Montreal", state: "QC", phone: "514-273-8410", mobile: "514-836-7499", createdAt: new Date().toISOString() },
  { id: "cust_177", name: "Moshe Feldman", nameHebrew: "משה פעלדמאן", address: "761 De L'epee", city: "Montreal", state: "QC", phone: "514-297-5338", mobile: "438-408-4245", createdAt: new Date().toISOString() },
  { id: "cust_178", name: "Alter Menachem Perl", nameHebrew: "אלטר מנחם פערל", address: "563 Querbes", city: "Montreal", state: "QC", phone: "514-276-3653", mobile: "514-991-0453", createdAt: new Date().toISOString() },
  { id: "cust_179", name: "Yoel Perl", nameHebrew: "יואל פערל", address: "5950 Hutchison", city: "Montreal", state: "QC", phone: "514-993-2632", mobile: "514-994-9079", createdAt: new Date().toISOString() },
  { id: "cust_180", name: "Mier Naftula Perl", nameHebrew: "מאיר נפתלי פערל", address: "769 A Querbes", city: "Montreal", state: "QC", phone: "514-662-6752", mobile: "438-528-3119", createdAt: new Date().toISOString() },
  { id: "cust_181", name: "Avrom Yechezkal Perlmutter", nameHebrew: "אברהם יחזקאל פערלמוטער", address: "1212 Lajoie", city: "Montreal", state: "QC", phone: "514-274-7250", mobile: "438-630-1013", createdAt: new Date().toISOString() },
  { id: "cust_182", name: "Yitzchok Noch Perlmutter", nameHebrew: "יצחק נח פערלמוטער", address: "5952 Durocher", city: "Montreal", state: "QC", phone: "514-278-3375", mobile: "514-501-6651", createdAt: new Date().toISOString() },
  // Page 7
  { id: "cust_183", name: "Alchunon Chaim Freund", nameHebrew: "אלחנן חיים פריינד", address: "740 De L'epee", city: "Montreal", state: "QC", phone: "514-419-1899", mobile: "438-937-7009", createdAt: new Date().toISOString() },
  { id: "cust_184", name: "Shia Freund", nameHebrew: "יושע פריינד", address: "830 Champagneur", city: "Montreal", state: "QC", phone: "514-573-1637", mobile: "438-630-1367", createdAt: new Date().toISOString() },
  { id: "cust_185", name: "Avrum Hersh Fried", nameHebrew: "אברהם הערש פריעד", address: "425 Querbes", city: "Montreal", state: "QC", phone: "514-273-3680", mobile: "514-591-9039", createdAt: new Date().toISOString() },
  { id: "cust_186", name: "Lipa Fried", nameHebrew: "חנני' יו\"ט ליפא פריעד", address: "5882 Durocher", city: "Montreal", state: "QC", phone: "514-692-7497", mobile: "438-365-3347", createdAt: new Date().toISOString() },
  { id: "cust_187", name: "Matesyue Friedlander", nameHebrew: "אהרן מתתי' פריעדלענדער", address: "5722 Hutchison", city: "Montreal", state: "QC", phone: "514-277-7001", createdAt: new Date().toISOString() },
  { id: "cust_188", name: "Zalmen Leib Friedman", nameHebrew: "זלמן לייב פריעדמאן", address: "5190 Durocher", city: "Montreal", state: "QC", phone: "514-279-9482", mobile: "514-927-9482", createdAt: new Date().toISOString() },
  { id: "cust_189", name: "Yoel Friedman", nameHebrew: "יואל פריעדמאן", address: "372 De L'epee", city: "Montreal", state: "QC", phone: "514-276-4185", mobile: "514-965-4841", createdAt: new Date().toISOString() },
  { id: "cust_190", name: "Yechesckel Friedman", nameHebrew: "יחזקאל שרגא פריעדמאן", address: "457 Outremont", city: "Montreal", state: "QC", phone: "514-270-0584", mobile: "514-794-0585", createdAt: new Date().toISOString() },
  { id: "cust_191", name: "Yisruel Friedman", nameHebrew: "ישראל פריעדמאן", address: "5712 Durocher", city: "Montreal", state: "QC", phone: "514-272-4338", mobile: "514-712-4338", createdAt: new Date().toISOString() },
  { id: "cust_192", name: "Moshe yakov Friedman", nameHebrew: "משה יעקב פריעדמאן", address: "286 De L'epee", city: "Montreal", state: "QC", phone: "514-277-0779", mobile: "514-892-6011", createdAt: new Date().toISOString() },
  { id: "cust_193", name: "Meshilem Friedman", nameHebrew: "משולם פייוויש פריעדמאן", address: "685 Bloomfield", city: "Montreal", state: "QC", phone: "514-419-2519", mobile: "438-365-1484", createdAt: new Date().toISOString() },
  { id: "cust_194", name: "Mayer Friedman", nameHebrew: "מאיר פריעדמאן", address: "5470 Hutchison", city: "Montreal", state: "QC", mobile: "438-365-1867", createdAt: new Date().toISOString() },
  { id: "cust_195", name: "Simon Yisruel Friedman", nameHebrew: "שמעון ישראל פריעדמאן", address: "680 Outremont", city: "Montreal", state: "QC", phone: "514-279-6985", mobile: "514-570-5724", createdAt: new Date().toISOString() },
  { id: "cust_196", name: "Shmaye Friedman", nameHebrew: "שמעי' פריעדמאן", address: "287 De L'epee", city: "Montreal", state: "QC", phone: "514-276-8153", mobile: "845-750-5715", createdAt: new Date().toISOString() },
  { id: "cust_197", name: "Yakov meir Frankel", nameHebrew: "יעקב מאיר פרענקל", address: "745 Outremont", city: "Montreal", state: "QC", phone: "514-276-9072", mobile: "438-379-1055", createdAt: new Date().toISOString() },
  { id: "cust_198", name: "Yitzchok Frankel", nameHebrew: "יצחק פרענקל", address: "274 De L'epee", city: "Montreal", state: "QC", phone: "514-272-4032", mobile: "514-963-9568", createdAt: new Date().toISOString() },
  { id: "cust_199", name: "Shmeil Zanvil Frankel", nameHebrew: "שמואל זאנוויל פרענקל", address: "5954 Hutchison", city: "Montreal", state: "QC", phone: "514-279-2429", mobile: "514-298-4324", createdAt: new Date().toISOString() },
  { id: "cust_200", name: "yoel mordcha arya Frankel", nameHebrew: "יואל מרדכי ארי' פרענקל", address: "5571 Hutchison", city: "Montreal", state: "QC", mobile: "438-493-8569", createdAt: new Date().toISOString() },
  { id: "cust_201", name: "Aron Doniel Zimment", nameHebrew: "אהרן דניאל צימענד", address: "5927 Esplanade", city: "Montreal", state: "QC", mobile: "438-881-2539", createdAt: new Date().toISOString() },
  { id: "cust_202", name: "Yackov Zimmerman", nameHebrew: "יעקב צימערמאן", address: "5308 Hutchison", city: "Montreal", state: "QC", phone: "514-277-2848", mobile: "438-345-4683", createdAt: new Date().toISOString() },
  { id: "cust_203", name: "Abraham Tzin", nameHebrew: "אברהם שלמה צין", address: "151 De L'epee", city: "Montreal", state: "QC", phone: "514-273-1206", mobile: "438-529-6241", createdAt: new Date().toISOString() },
  { id: "cust_204", name: "Yoel Moshe Czik", nameHebrew: "יואל משה ציק", address: "5363 Jeanne Mance", city: "Montreal", state: "QC", phone: "514-270-4721", mobile: "514-922-4722", createdAt: new Date().toISOString() },
  { id: "cust_205", name: "Chanoch Tzinner", nameHebrew: "חנוך שלום ציננער", address: "6194 Durocher", city: "Montreal", state: "QC", phone: "438-493-3209", mobile: "438-543-3339", createdAt: new Date().toISOString() },
  { id: "cust_206", name: "Benzion Duvid Kohn", nameHebrew: "בן ציון דוד קאהן", address: "761 De L'epee", city: "Montreal", state: "QC", createdAt: new Date().toISOString() },
  { id: "cust_207", name: "Yoel Kohn", nameHebrew: "יואל קאהן", address: "6090 Durocher", city: "Montreal", state: "QC", phone: "514-277-7720", mobile: "438-932-7720", createdAt: new Date().toISOString() },
  { id: "cust_208", name: "Yisroel Kohn", nameHebrew: "ישראל קאהן", address: "386 Wiseman", city: "Montreal", state: "QC", phone: "514-279-0579", mobile: "514-963-2969", createdAt: new Date().toISOString() },
  { id: "cust_209", name: "Simcha Kohn", nameHebrew: "שמחה בונם קאהן", address: "198 Querbes", city: "Montreal", state: "QC", mobile: "347-786-4711", createdAt: new Date().toISOString() },
  { id: "cust_210", name: "Duvid Kalish", nameHebrew: "דוד קאליש", address: "792 Champagneur", city: "Montreal", state: "QC", phone: "514-543-7226", mobile: "438-490-3356", createdAt: new Date().toISOString() },
  { id: "cust_211", name: "Avrum Wolf Kaufman", nameHebrew: "אברהם וואלף קויפמאן", address: "325 De L'epee", city: "Montreal", state: "QC", phone: "514-279-5901", mobile: "514-806-8458", createdAt: new Date().toISOString() },
  { id: "cust_212", name: "Aron Kaufman", nameHebrew: "אהרן קויפמאן", address: "5283 Jeanne Mance", city: "Montreal", state: "QC", phone: "514-277-3709", mobile: "514-402-4841", createdAt: new Date().toISOString() },
  { id: "cust_213", name: "Yoel Kaufman", nameHebrew: "יואל קויפמאן", address: "5148 Hutchison", city: "Montreal", state: "QC", phone: "514-274-6566", mobile: "438-345-4625", createdAt: new Date().toISOString() },
  // Page 8
  { id: "cust_214", name: "Yitzchok Kaufman", nameHebrew: "יצחק צבי קויפמאן", address: "761 De L'epee", city: "Montreal", state: "QC", mobile: "917-703-1479", createdAt: new Date().toISOString() },
  { id: "cust_215", name: "Moshe Nusen Katina", nameHebrew: "משה נתן קטינא", address: "5313 Hutchison", city: "Montreal", state: "QC", phone: "514-274-4639", mobile: "514-796-9125", createdAt: new Date().toISOString() },
  { id: "cust_216", name: "Alter Moshe Klein", nameHebrew: "אלטר משה קליין", address: "1045 St. Viateur", city: "Montreal", state: "QC", phone: "514-507-8583", mobile: "438-506-8583", createdAt: new Date().toISOString() },
  { id: "cust_217", name: "Eliezer Klein", nameHebrew: "אליעזר קליין", address: "430 Wiseman", city: "Montreal", state: "QC", phone: "514-490-0087", mobile: "514-817-3844", createdAt: new Date().toISOString() },
  { id: "cust_218", name: "Eluzer klein", nameHebrew: "אלעזר קליין", address: "726 A Champagneur", city: "Montreal", state: "QC", phone: "514-662-7497", mobile: "438-879-9991", createdAt: new Date().toISOString() },
  { id: "cust_219", name: "Berl klein", nameHebrew: "בערל קליין", address: "6070 Hutchison", city: "Montreal", state: "QC", mobile: "438-530-1993", createdAt: new Date().toISOString() },
  { id: "cust_220", name: "Hershel Klein", nameHebrew: "הערשל קליין", address: "555 Querbes", city: "Montreal", state: "QC", phone: "514-495-1744", mobile: "514-347-2864", createdAt: new Date().toISOString() },
  { id: "cust_221", name: "Yoel Klein", nameHebrew: "יואל קליין", address: "5153 Durocher", city: "Montreal", state: "QC", phone: "514-279-5609", mobile: "514-692-5609", createdAt: new Date().toISOString() },
  { id: "cust_222", name: "Yechiel Klein", nameHebrew: "יחיאל קליין", address: "5331 Hutchison", city: "Montreal", state: "QC", phone: "514-495-3913", mobile: "514-668-2921", createdAt: new Date().toISOString() },
  { id: "cust_223", name: "Menachem Klein", nameHebrew: "מנחם זאב קליין", address: "467 Querbes", city: "Montreal", state: "QC", phone: "514-273-6966", mobile: "438-354-8499", createdAt: new Date().toISOString() },
  { id: "cust_224", name: "Yechiel Shraga Knophler", nameHebrew: "יחיאל שרגא קנאפללער", address: "506 Bloomfield", city: "Montreal", state: "QC", phone: "514-277-5181", mobile: "845-604-1896", createdAt: new Date().toISOString() },
  { id: "cust_225", name: "Shneur Zalman Koenig", nameHebrew: "שניאור זלמן קעניג", address: "4G9 H2V", city: "Montreal", state: "QC", mobile: "438-990-9192", createdAt: new Date().toISOString() },
  { id: "cust_226", name: "Moshe Quesada", nameHebrew: "משה קעסאדע", address: "5255 Parc Ave.", city: "Montreal", state: "QC", mobile: "438-525-1691", createdAt: new Date().toISOString() },
  { id: "cust_227", name: "Mordche Yona Krausz", nameHebrew: "מרדכי יונה קרויס", address: "660 Bloomfield", city: "Montreal", state: "QC", phone: "514-867-6282", mobile: "929-486-6282", createdAt: new Date().toISOString() },
  { id: "cust_228", name: "Shmiel Rosner", nameHebrew: "שמואל ראזנער", address: "6142 Durocher", city: "Montreal", state: "QC", phone: "514-227-0759", mobile: "514-562-7708", createdAt: new Date().toISOString() },
  { id: "cust_229", name: "Joel Rosenberg", nameHebrew: "יואל ראזענבערג", address: "367 Querbes", city: "Montreal", state: "QC", mobile: "514-922-7963", createdAt: new Date().toISOString() },
  { id: "cust_230", name: "Alter Shaya Rosenvaser", nameHebrew: "אלטר ישעי' ראזענוואסער", address: "5857 Hutchison", city: "Montreal", state: "QC", phone: "514-276-8973", mobile: "845-537-7320", createdAt: new Date().toISOString() },
  { id: "cust_231", name: "Yoel Rosenfeld", nameHebrew: "יואל ראזענפעלד", address: "1124 St. Viateur", city: "Montreal", state: "QC", phone: "514-271-2692", mobile: "514-967-2692", createdAt: new Date().toISOString() },
  { id: "cust_232", name: "Yoel Rosenfeld", nameHebrew: "יואל ראזענפעלד", address: "453 Outremont", city: "Montreal", state: "QC", phone: "514-271-1145", mobile: "438-530-1145", createdAt: new Date().toISOString() },
  { id: "cust_233", name: "David Rutbard", nameHebrew: "דוד ראטבארד", address: "5617 Hutchison", city: "Montreal", state: "QC", phone: "514-277-7977", mobile: "514-809-1762", createdAt: new Date().toISOString() },
  { id: "cust_234", name: "Siny Roth", nameHebrew: "סיני ראטה", address: "510 Outremont", city: "Montreal", state: "QC", phone: "514-277-2353", mobile: "514-836-9484", createdAt: new Date().toISOString() },
  { id: "cust_235", name: "Shlome Yeceskel Rubin", nameHebrew: "שלמה יחזקאל רובין", address: "367 De L'epee", city: "Montreal", state: "QC", phone: "438-882-9473", mobile: "438-883-9473", createdAt: new Date().toISOString() },
  { id: "cust_236", name: "Yakev Reisman", nameHebrew: "יצחק יעקב רייזמאן", address: "789 Champagneur", city: "Montreal", state: "QC", phone: "514-270-9869", mobile: "514-772-1356", createdAt: new Date().toISOString() },
  { id: "cust_237", name: "Chaim Burech Reich", nameHebrew: "חיים ברוך רייך", address: "1134 St. Viateur", city: "Montreal", state: "QC", phone: "514-418-2095", mobile: "514-545-2068", createdAt: new Date().toISOString() },
  { id: "cust_238", name: "Shlome Retek", nameHebrew: "שלמה רעטעק", address: "5814 Durocher", city: "Montreal", state: "QC", phone: "514-271-4583", createdAt: new Date().toISOString() },
  { id: "cust_239", name: "Mrs Soloman", nameHebrew: "שמעי' שאלאמאן", address: "1062 St. Viateur", city: "Montreal", state: "QC", phone: "514-273-4097", mobile: "438-935-4097", createdAt: new Date().toISOString() },
  { id: "cust_240", name: "Nechemye Shafer", nameHebrew: "נחמי' שאפער", address: "234 Querbes", city: "Montreal", state: "QC", phone: "514-276-2099", mobile: "438-622-8895", createdAt: new Date().toISOString() },
  { id: "cust_241", name: "Avrum Abir Schwartz", nameHebrew: "אברהם עביר שווארטץ", address: "767 Querbes", city: "Montreal", state: "QC", phone: "514-276-0246", createdAt: new Date().toISOString() },
  { id: "cust_242", name: "Aron Moshe Schwartz", nameHebrew: "אהרן משה שווארטץ", address: "5186 Durocher", city: "Montreal", state: "QC", phone: "514-274-4658", mobile: "514-885-4658", createdAt: new Date().toISOString() },
  { id: "cust_243", name: "Zalmon Leib Schwartz", nameHebrew: "זלמן לייב שווארטץ", address: "5403 Durocher", city: "Montreal", state: "QC", phone: "450-419-1605", mobile: "514-627-4989", createdAt: new Date().toISOString() },
  { id: "cust_244", name: "Yitzchok Schwartz", nameHebrew: "יצחק שווארטץ", address: "6057 Hutchison", city: "Montreal", state: "QC", phone: "438-375-4192", mobile: "438-831-3132", createdAt: new Date().toISOString() },
  // Page 9
  { id: "cust_245", name: "Lipe Schwartz", nameHebrew: "ליפא שווארטץ", address: "735 Bloomfield", city: "Montreal", state: "QC", phone: "438-543-6743", mobile: "450-830-9777", createdAt: new Date().toISOString() },
  { id: "cust_246", name: "Moshe Schwartz", nameHebrew: "משה שווארטץ", address: "780 Querbes", city: "Montreal", state: "QC", phone: "514-274-8610", mobile: "514-963-4893", createdAt: new Date().toISOString() },
  { id: "cust_247", name: "Shulem Schwartz", nameHebrew: "שלום שווארטץ", address: "261 De L'epee", city: "Montreal", state: "QC", mobile: "514-261-6772", createdAt: new Date().toISOString() },
  { id: "cust_248", name: "Yoel Moishe Shtul", nameHebrew: "יואל משה שטוהל", address: "768 A Bloomfield", city: "Montreal", state: "QC", phone: "438-384-3034", mobile: "438-501-3034", createdAt: new Date().toISOString() },
  { id: "cust_249", name: "Moshe Chaim Stein", nameHebrew: "משה חיים שטיין", address: "527 Querbes", city: "Montreal", state: "QC", phone: "514-903-1773", mobile: "438-389-6708", createdAt: new Date().toISOString() },
  { id: "cust_250", name: "Avrum Afraim Stern", nameHebrew: "אברהם אפרים שטערן", address: "750 Bloomfield", city: "Montreal", state: "QC", phone: "514-968-4861", mobile: "514-464-5138", createdAt: new Date().toISOString() },
  { id: "cust_251", name: "Yoel Stern", nameHebrew: "יואל שטערן", address: "5140 Durocher", city: "Montreal", state: "QC", phone: "514-270-5901", mobile: "438-937-1059", createdAt: new Date().toISOString() },
  { id: "cust_252", name: "Yida Stern", nameHebrew: "יהודה שטערן", address: "5642 Durocher", city: "Montreal", state: "QC", phone: "514-227-0957", mobile: "514-701-0957", createdAt: new Date().toISOString() },
  { id: "cust_253", name: "Yisreol Stern", nameHebrew: "ישראל שטערן", address: "5445 Durocher", city: "Montreal", state: "QC", phone: "514-507-9728", mobile: "438-509-9726", createdAt: new Date().toISOString() },
  { id: "cust_254", name: "Menachem Zev Stern", nameHebrew: "מנחם זאב שטערן", address: "727 Querbes", city: "Montreal", state: "QC", phone: "514-270-2422", mobile: "514-927-8610", createdAt: new Date().toISOString() },
  { id: "cust_255", name: "Moshe Shtrasser", nameHebrew: "משה שטראססער", address: "718 De L'epee", city: "Montreal", state: "QC", phone: "514-270-5232", mobile: "514-216-8512", createdAt: new Date().toISOString() },
  { id: "cust_256", name: "Avrum Schnitzler", nameHebrew: "אברהם שניטצלער", address: "501 Querbes", city: "Montreal", state: "QC", phone: "514-267-9019", mobile: "438-998-4221", createdAt: new Date().toISOString() },
  { id: "cust_257", name: "Duvid Meir Shnitzer", nameHebrew: "דוד מאיר שניטצער", address: "5333 Hutchison", city: "Montreal", state: "QC", mobile: "438-526-3335", createdAt: new Date().toISOString() },
  { id: "cust_258", name: "Yakov Shneider", nameHebrew: "יעקב אברהם שניידער", address: "1033 Van Horne", city: "Montreal", state: "QC", phone: "514-271-6999", createdAt: new Date().toISOString() },
  { id: "cust_259", name: "Chaim Scher", nameHebrew: "חיים יקותיאל שעהר", address: "543 Outremont", city: "Montreal", state: "QC", mobile: "579-366-5120", createdAt: new Date().toISOString() },
  { id: "cust_260", name: "Mordchai Scher", nameHebrew: "מרדכי שעהר", address: "5226 Hutchison", city: "Montreal", state: "QC", phone: "514-272-1510", mobile: "514-999-6220", createdAt: new Date().toISOString() },
  { id: "cust_261", name: "Meir Moshe Spitzer", nameHebrew: "מאיר משה שפיטצער", address: "704 Champagneur", city: "Montreal", state: "QC", phone: "514-903-5809", mobile: "438-939-6818", createdAt: new Date().toISOString() },
  { id: "cust_262", name: "Moshe Spitzer", nameHebrew: "משה שפיטצער", address: "5862 Durocher", city: "Montreal", state: "QC", phone: "514-272-3472", mobile: "514-824-9095", createdAt: new Date().toISOString() },
  { id: "cust_263", name: "Shlome Yakov Spitzer", nameHebrew: "שלמה יעקב שפיטצער", address: "459 Outremont", city: "Montreal", state: "QC", phone: "514-277-5361", mobile: "438-506-2633", createdAt: new Date().toISOString() },
  { id: "cust_264", name: "Amrom nusan shpilman", nameHebrew: "עמרם נתן שפילמאן", address: "5930 Hutchison", city: "Montreal", state: "QC", phone: "514-270-1134", mobile: "438-530-1134", createdAt: new Date().toISOString() },
  { id: "cust_265", name: "Aron Hersh Shrieber", nameHebrew: "אהרן צבי שרייבער", address: "5864 Hutchison", city: "Montreal", state: "QC", mobile: "438-529-7769", createdAt: new Date().toISOString() },
  { id: "cust_266", name: "Yehuda Shrieber", nameHebrew: "יודא שרייבער", address: "742 A Querbes", city: "Montreal", state: "QC", createdAt: new Date().toISOString() },
];
