import { Customer } from "@/types";

export const INITIAL_CUSTOMERS_DATA: Customer[] = [
  {
    id: "cust_001",
    name: "Burech Mordche Oberlander",
    nameHebrew: "ברוך מרדכי אבערלענדער",
    address: "1160 Lajoie",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1N9",
    phone: "514-271-5492",
    mobile: "514-223-8210",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_002",
    name: "Shloma Oberlander",
    nameHebrew: "שלמה אבערלענדער",
    address: "704 Champagneur",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3P8",
    phone: "514-223-6862",
    mobile: "514-404-6862",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_003",
    name: "Moshe Oberlander",
    nameHebrew: "משה אבערלענדער",
    address: "Montreal",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_004",
    name: "Shloma Yitzchok Unger",
    nameHebrew: "שלמה יצחק אונגאר",
    address: "5689 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K4",
    phone: "438-503-4683",
    mobile: "438-378-6786",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_005",
    name: "Chaim Unger",
    nameHebrew: "חיים יהושע אשר אונגער",
    address: "5840 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y4",
    phone: "438-375-9711",
    mobile: "438-491-9711",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_006",
    name: "Yakov Duvid Eisdorfer",
    nameHebrew: "יעקב דוד אייזדארפער",
    address: "Montreal",
    city: "Montreal",
    state: "QC",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_007",
    name: "Eizen",
    nameHebrew: "יעקב אייזען",
    address: "5880 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3Y4",
    phone: "514-574-3055",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_008",
    name: "Shimon Altman",
    nameHebrew: "שמעון אלטמאן",
    address: "6062 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K8",
    phone: "514-273-8221",
    mobile: "514-830-0542",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_009",
    name: "Yoel Itzkowitz",
    nameHebrew: "יואל איצקאוויטש",
    address: "747 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S4",
    phone: "514-278-9519",
    mobile: "514-963-9519",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_010",
    name: "Shmiel Yide Itzkowitz",
    nameHebrew: "שמואל יודא איצקאוויטש",
    address: "181 De L'epee",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3T1",
    phone: "514-270-4097",
    mobile: "438-404-3165",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_011",
    name: "Yakov Hersh Appeldorfer",
    nameHebrew: "יעקב הערש אפעלדארפער",
    address: "780 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3W9",
    phone: "514-279-1967",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_012",
    name: "Cheskel Appel",
    nameHebrew: "יחזקאל שרגא אפפעל",
    address: "663 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S2",
    mobile: "917-748-0764",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_013",
    name: "Yoel Ackerman",
    nameHebrew: "יואל אקערמאן",
    address: "304 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3W3",
    phone: "514-272-6294",
    mobile: "438-764-6299",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_014",
    name: "Yisroel Ackerman",
    nameHebrew: "ישראל אקערמאן",
    address: "6096 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1X6",
    phone: "514-274-2032",
    mobile: "263-993-2399",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_015",
    name: "Mordechai Orgel",
    nameHebrew: "מרדכי ארגעל",
    address: "5192 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3X8",
    mobile: "450-949-0055",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_016",
    name: "Rabbi Chaim Ashkenazi",
    nameHebrew: "הרב חיים אשכנזי שליט\"א",
    address: "149 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3V8",
    phone: "514-313-6563",
    mobile: "438-878-6563",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_017",
    name: "Arye Buchinger",
    nameHebrew: "ארי' בוכינגער",
    address: "633 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S2",
    phone: "514-276-9932",
    mobile: "438-995-7968",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_018",
    name: "Yakov Bikel",
    nameHebrew: "יעקב ביקעל",
    address: "5641 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B5",
    phone: "514-495-6545",
    mobile: "514-992-9077",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_019",
    name: "Lipa Blumentahl",
    nameHebrew: "ליפא בלומענטאל",
    address: "5379 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3X9",
    phone: "514-271-4097",
    mobile: "514-738-2700",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_020",
    name: "Mordechai Blumentahl",
    nameHebrew: "מרדכי בלומענטאל",
    address: "6056 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V 4C2",
    mobile: "845-662-3000",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_021",
    name: "Yisrul Blier",
    nameHebrew: "ישראל בלייער",
    address: "5686 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y2",
    phone: "514-274-1973",
    mobile: "514-568-7998",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_022",
    name: "Yoel Berger",
    nameHebrew: "יואל ברי\"ט בערגער",
    address: "760 De L'epee",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3T9",
    mobile: "845-502-1616",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_023",
    name: "Yoel Berger",
    nameHebrew: "יואל בערגער",
    address: "6128 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K8",
    phone: "514-272-2363",
    mobile: "514-250-2363",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_024",
    name: "Yisruel Moshe Brody",
    nameHebrew: "ישראל משה בראדי",
    address: "5239 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B4",
    phone: "514-279-5856",
    mobile: "514-830-6405",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_025",
    name: "Shlome Yide Broder",
    nameHebrew: "שלמה יודא בראדער",
    address: "6071 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y7",
    phone: "514-224-1341",
    mobile: "438-389-5078",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_026",
    name: "Elimilech Brach",
    nameHebrew: "אלימלך בראך",
    address: "1371 Lajoie",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1P6",
    phone: "514-495-4056",
    mobile: "514-963-4056",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_027",
    name: "Eliazer Leib Brach",
    nameHebrew: "אליעזר לייב בראך",
    address: "21 Duverger",
    city: "Montreal",
    state: "QC",
    zip: "H2V 1M9",
    mobile: "646-864-6854",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_028",
    name: "Pinchus Brach",
    nameHebrew: "פנחס בראך",
    address: "5724 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B6",
    phone: "514-277-1522",
    mobile: "514-691-4862",
    createdAt: new Date().toISOString()
  },
  // Page 2
  {
    id: "cust_029",
    name: "Yisrul Brief",
    nameHebrew: "ישראל בריעף",
    address: "5714 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y2",
    mobile: "438-365-1595",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_030",
    name: "Hershel Goldberger",
    nameHebrew: "בנציון צבי גאלדבערגער",
    address: "25 Laviolette",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1X6",
    phone: "514-271-5651",
    mobile: "514-806-5651",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_031",
    name: "Yoel Goldberger",
    nameHebrew: "יואל גאלדבערגער",
    address: "5850 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4C1",
    phone: "514-272-4598",
    mobile: "514-586-4598",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_032",
    name: "Mordche Arye Goldberger",
    nameHebrew: "מרדכי ארי' גאלדבערגער",
    address: "5432 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B3",
    phone: "514-274-5245",
    mobile: "438-994-4599",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_033",
    name: "Mendel Goldberger",
    nameHebrew: "מנחם מענדל גאלדבערגער",
    address: "5847 Parc",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4H4",
    mobile: "438-764-2268",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_034",
    name: "Shimon Goldberger",
    nameHebrew: "שמעון גאלדבערגער",
    address: "5281 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4K3",
    phone: "514-276-7926",
    mobile: "438-630-7296",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_035",
    name: "Yoel Goldman",
    nameHebrew: "יואל גאלדמאן",
    address: "5967 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y5",
    phone: "514-272-0060",
    mobile: "438-938-8409",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_036",
    name: "Mordche Hersh Goldman",
    nameHebrew: "מרדכי הערש גאלדמאן",
    address: "6069 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B7",
    phone: "514-274-9027",
    mobile: "514-913-9027",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_037",
    name: "Duvid Goldstein",
    nameHebrew: "דוד גאלדשטיין",
    address: "480 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3R8",
    mobile: "845-395-8185",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_038",
    name: "Yisruel Shulem Gandel",
    nameHebrew: "ישראל שלום גאנدل",
    address: "656 Querbes",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3W8",
    phone: "514-903-7776",
    mobile: "438-509-5261",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_039",
    name: "Chaim Yakov Guttman",
    nameHebrew: "חיים יעקב גוטטמאן",
    address: "867 McEachren",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3C9",
    phone: "514-992-5090",
    mobile: "438-878-8352",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_040",
    name: "Yossef Guttman",
    nameHebrew: "יוסף גוטטמאן",
    address: "1248 Lajoie",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1P1",
    phone: "514-277-3768",
    mobile: "438-398-8412",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_041",
    name: "Menachem Mandel Guttman",
    nameHebrew: "מנחם מע德尔 גוטטמאן",
    address: "687 Bloomfield",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3S2",
    phone: "514-313-1034",
    mobile: "438-876-7616",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_042",
    name: "Pinchus Glauber",
    nameHebrew: "פנחס גלויבער",
    address: "735 A Champagneur",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3P9",
    phone: "514-272-2063",
    mobile: "438-938-9136",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_043",
    name: "Hersh Elimeilech Glick",
    nameHebrew: "הערש אלימלך גליק",
    address: "5342 Esplanade",
    city: "Montreal",
    state: "QC",
    zip: "H2T-2Z7",
    phone: "514-495-8642",
    mobile: "514-885-8640",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_044",
    name: "Akive Peisech Glick",
    nameHebrew: "עקיבא פסח גליק",
    address: "709 Champagneur",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3P9",
    phone: "514-271-0542",
    mobile: "514-452-4175",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_045",
    name: "Yida Moshe Gelb",
    nameHebrew: "יודא משה געלב",
    address: "358 De L'epee",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3T6",
    phone: "514-277-0388",
    mobile: "514-531-3504",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_046",
    name: "Moshe Eliezer Gestetner",
    nameHebrew: "משה אליעזר געויטנער",
    address: "5252 Jeanne Mance",
    city: "Montreal",
    state: "QC",
    zip: "H2V 4K4",
    mobile: "514-358-6428",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_047",
    name: "Berish Gross",
    nameHebrew: "בע里斯 גראס",
    address: "5269 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B4",
    phone: "514-276-9312",
    mobile: "514-993-5273",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_048",
    name: "Yidel Gross",
    nameHebrew: "יקותיאל יודא צבי גראס",
    address: "780 B Champagneur",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3P8",
    mobile: "845-772-5490",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_049",
    name: "Mordche Gross",
    nameHebrew: "מרדכי גראס",
    address: "5714 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V-4B6",
    phone: "514-270-6668",
    mobile: "514-963-6668",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_050",
    name: "Mrs Shmiel Gruber",
    nameHebrew: "מרת שמואל גרובער",
    address: "5462 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V 4B3",
    phone: "514-467-2784",
    mobile: "514-463-7287",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_051",
    name: "Yoel Yeshea Green",
    nameHebrew: "יואל יושע גרין",
    address: "737 A De L'epee",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3V1",
    phone: "514-240-4008",
    mobile: "514-880-6731",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_052",
    name: "Shaul Chezkel Greenfeld",
    nameHebrew: "שאול יחזקאל גרינפעלד",
    address: "5581 Hutchison",
    city: "Montreal",
    state: "QC",
    zip: "H2V 4B5",
    phone: "514-885-7311",
    mobile: "514-424-7311",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_053",
    name: "Nusen Binyomin Grintzweig",
    nameHebrew: "נתן בנימין גרינצווייג",
    address: "1044 St. Viateur",
    city: "Montreal",
    state: "QC",
    zip: "H2V-1Y3",
    mobile: "514-550-5329",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_054",
    name: "Mordchai Danziger",
    nameHebrew: "מרדכי דאנציגער",
    address: "5839 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V 3Y5",
    phone: "514-276-2942",
    mobile: "438-876-6942",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_055",
    name: "Yoel Shaye Deutch",
    nameHebrew: "יואל ישעי' דייטש",
    address: "5459 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3X9",
    phone: "514-273-1773",
    mobile: "514-815-6876",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_056",
    name: "Avrum Yosef Drummer",
    nameHebrew: "אברהם יוסף דרוממער",
    address: "5781 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y3",
    phone: "514-272-0342",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_057",
    name: "Chaim Drezner",
    nameHebrew: "חיים דרעזנער",
    address: "1140 Lajoie",
    city: "Montreal",
    state: "QC",
    zip: "H2V 1N8",
    phone: "514-979-8642",
    mobile: "438-506-6345",
    createdAt: new Date().toISOString()
  },
  {
    id: "cust_058",
    name: "Yoel Drezner",
    nameHebrew: "יואל דרעזנער",
    address: "6032 Durocher",
    city: "Montreal",
    state: "QC",
    zip: "H2V-3Y6",
    phone: "514-272-0928",
    mobile: "514-867-7389",
    createdAt: new Date().toISOString()
  },
];
