// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export type Database = {
  // Define your database schema here
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add error handling for network issues
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_OUT') {
    console.log('User signed out');
  }
});

// Add network monitoring
supabase.rpc('ping', {}).then(response => {
  if (response.data === 'pong') {
    console.log('Connected to Supabase');
  } else {
    console.error('Ping failed:', response.error);
  }
}).catch(error => {
  console.error('Network error:', error);
});