<![CDATA[// This file is automatically generated. Do not edit it directly.
import { supabase } from "@/integrations/supabase/client";
import { Customer, Product, Order, OrderItem, Settings, Payment, InventoryEntry } from "@/types";

export const supabaseService = {
  // --- Customers ---
  async getCustomers(retries = 3): Promise<Customer[]> {
    console.log(`🔍 Fetching customers from Supabase... (Retries left: ${retries})`);

    try {
      const { data, error } = await supabase
        .from("customers")
        .select("*")
        .order("name");

      if (error) {
        console.error("❌ Error fetching customers (Supabase response error):", error);
        if (retries > 0) {
          console.log("Retrying...");
          await new Promise(res => setTimeout(res, 1000)); // Wait 1 second before retrying
          return this.getCustomers(retries - 1);
        }
        return [];
      }

      if (!data) {
        console.warn("⚠️ Supabase returned no data for customers (data is null/undefined).");
        return [];
      }

      console.log("✅ Successfully fetched customers:", data.length);

      return data.map((c: any) => ({
        id: c.id,
        name: c.name,
        nameHebrew: c.name_hebrew,
        titleHebrew: c.title_hebrew,
        titleEnglish: c.title_english,
        firstNameHebrew: c.first_name_hebrew,
        lastNameHebrew: c.last_name_hebrew,
        firstName: c.first_name,
        lastName: c.last_name,
        houseNumber: c.house_number,
        apt: c.apt,
        street: c.street,
        email: c.email,
        phone: c.phone,
        mobile: c.mobile,
        address: c.address,
        city: c.city,
        state: c.state,
        zip: c.zip,
        notes: c.notes,
        createdAt: c.created_at
      }));
    } catch (err) {
      console.error("🔥 Network or unexpected error while fetching customers:", err);
      
      // If it's a network failure (like Failed to fetch), retry!
      if (retries > 0) {
        console.log("Network failure. Retrying...");
        await new Promise(res => setTimeout(res, 1500)); // Wait 1.5 seconds before retrying
        return this.getCustomers(retries - 1);
      }
      return [];
    }
  },

  async getCustomer(id: string): Promise<Customer | null> {
    const { data, error } = await supabase
      .from('customers')
      .select('*')
      .eq('id', id)
      .single();
      
    if (error || !data) {
      console.error('Error fetching customer:', error);
      return null;
    }
    
    return {
      id: data.id,
      name: data.name,
      nameHebrew: data.name_hebrew,
      titleHebrew: data.title_hebrew,
      titleEnglish: data.title_english,
      firstNameHebrew: data.first_name_hebrew,
      lastNameHebrew: data.last_name_hebrew,
      firstName: data.first_name,
      lastName: data.last_name,
      houseNumber: data.house_number,
      apt: data.apt,
      street: data.street,
      email: data.email,
      phone: data.phone,
      mobile: data.mobile,
      address: data.address,
      city: data.city,
      state: data.state,
      zip: data.zip,
      notes: data.notes,
      createdAt: data.created_at
    };
  },

  async addCustomer(customer: Omit<Customer, "id" | "createdAt">): Promise<Customer | null> {
    const customerData = {
      name: customer.name,
      name_hebrew: customer.nameHebrew || null,
      title_hebrew: customer.titleHebrew || null,
      title_english: customer.titleEnglish || null,
      first_name_hebrew: customer.firstNameHebrew || null,
      last_name_hebrew: customer.lastNameHebrew || null,
      first_name: customer.firstName || null,
      last_name: customer.lastName || null,
      house_number: customer.houseNumber || null,
      apt: customer.apt || null,
      street: customer.street || null,
      email: customer.email || null,
      phone: customer.phone || null,
      mobile: customer.mobile || null,
      address: customer.address || null,
      city: customer.city || null,
      state: customer.state || null,
      zip: customer.zip || null,
      notes: customer.notes || null,
      created_at: new Date().toISOString(),
    };

    const { data, error } = await supabase
      .from('customers')
      .insert(customerData)
      .select()
      .single();

    if (error) {
      console.error('Error adding customer:', error);
      return null;
    }

    console.log('Customer added successfully:', data);

    return {
      id: data.id,
      name: data.name,
      nameHebrew: data.name_hebrew,
      titleHebrew: data.title_hebrew,
      titleEnglish: data.title_english,
      firstNameHebrew: data.first_name_hebrew,
      lastNameHebrew: data.last_name_hebrew,
      firstName: data.first_name,
      lastName: data.last_name,
      houseNumber: data.house_number,
      apt: data.apt,
      street: data.street,
      email: data.email,
      phone: data.phone,
      mobile: data.mobile,
      address: data.address,
      city: data.city,
      state: data.state,
      zip: data.zip,
      notes: data.notes,
      createdAt: data.created_at
    };
  },

  // --- Products ---
  async getProducts(): Promise<Product[]> {
    try {
      const { data, error } = await supabase
        .from("products")
        .select("*")
        .order("name");

      if (error) {
        console.error('Error fetching products:', error);
        return [];
      }

      return data.map((p: any) => ({
        id: p.id,
        name: p.name,
        nameHebrew: p.name_hebrew,
        pricePerLb: p.price_per_lb,
        category: p.category as Product["category"],
        description: p.description,
        inStock: p.in_stock,
        currentInventory: p.current_inventory
      }));
    } catch (err) {
      console.error("Network error fetching products:", err);
      return [];
    }
  },

  async updateProduct(product: Product): Promise<void> {
    const { error } = await supabase
      .from('products')
      .update({
        name: product.name,
        nameHebrew: product.nameHebrew,
        price_per_lb: product.pricePerLb,
        category: product.category,
        description: product.description,
        inStock: product.inStock,
        currentInventory: product.currentInventory
      })
      .eq('id', product.id);

    if (error) console.error('Error updating product:', error);
  },

  async addProduct(product: Omit<Product, "id">): Promise<Product | null> {
    const { data, error } = await supabase
      .from('products')
      .insert({
        name: product.name,
        name_hebrew: product.nameHebrew,
        price_per_lb: product.pricePerLb,
        category: product.category as string,
        description: product.description,
        inStock: product.inStock,
        currentInventory: product.currentInventory
      })
      .select()
      .single();

    if (error) {
      console.error('Error adding product:', error);
      return null;
    }

    return {
      id: data.id,
      name: data.name,
      nameHebrew: data.name_hebrew,
      pricePerLb: data.price_per_lb,
      category: data.category as Product["category"],
      description: data.description,
      inStock: data.inStock,
      currentInventory: data.current_inventory
    };
  },

  // --- Orders ---
  async getOrders(): Promise<Order[]> {
    try {
      const { data, error } = await supabase
        .from("orders")
        .select(`
          *,
          items:order_items(*)
        `)
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Error fetching orders:', error);
        return [];
      }

      return data.map((o: any) => ({
        id: o.id,
        orderNumber: o.order_number,
        customerId: o.customer_id,
        customerName: o.customer_name,
        customerEmail: o.customer_email,
        items: o.items.map((i: any) => ({
          productId: i.product_id,
          productName: i.product_name,
          productNameHebrew: i.product_name_hebrew,
          quantity: i.quantity,
          pricePerLb: i.price_per_lb,
          totalPrice: i.total_price,
          discount: i.discount,
          discountType: i.discount_type,
          finalPrice: i.final_price
        })),
        subtotal: o.subtotal,
        tax: o.tax,
        total: o.total,
        discount: o.discount,
        discountType: o.discount_type,
        status: o.status as "draft" | "pending" | "confirmed" | "preparing" | "ready" | "delivered" | "cancelled",
        paymentStatus: o.payment_status as "unpaid" | "partial" | "paid",
        amountPaid: o.amount_paid,
        amountDue: o.amount_due,
        notes: o.notes,
        deliveryDate: o.delivery_date,
        orderTime: o.order_time,
        inventoryDeducted: o.inventory_deducted,
        createdAt: o.created_at,
        updatedAt: o.updated_at
      }));
    } catch (err) {
      console.error("Network error fetching orders:", err);
      return [];
    }
  },

  async getOrder(id: string): Promise<Order | null> {
    const { data, error } = await supabase
      .from('orders')
      .select(`
        *,
        items:order_items(*)
      `)
      .eq('id', id)
      .single();

    if (error || !data) {
      console.error('Error fetching order:', error);
      return null;
    }

    return {
      id: data.id,
      orderNumber: data.order_number,
      customerId: data.customer_id,
      customerName: data.customer_name,
      customerEmail: data.customer_email,
      items: data.items.map((i: any) => ({
        productId: i.product_id,
        productName: i.product_name,
        productNameHebrew: i.product_name_hebrew,
        quantity: i.quantity,
        pricePerLb: i.price_per_lb,
        totalPrice: i.total_price,
        discount: i.discount,
        discountType: i.discount_type,
        finalPrice: i.final_price
      })),
      subtotal: data.subtotal,
      tax: data.tax,
      total: data.total,
      discount: data.discount,
      discountType: data.discount_type,
      status: data.status as "draft" | "pending" | "confirmed" | "preparing" | "ready" | "delivered" | "cancelled",
      paymentStatus: data.payment_status as "unpaid" | "partial" | "paid",
      amountPaid: data.amount_paid,
      amountDue: data.amount_due,
      notes: data.notes,
      deliveryDate: data.delivery_date,
      orderTime: data.order_time,
      inventoryDeducted: data.inventory_deducted,
      createdAt: data.created_at,
      updatedAt: data.updated_at
    };
  },

  async addOrder(order: Omit<Order, "id" | "createdAt" | "orderNumber" | "paymentStatus" | "amountPaid" | "amountDue" | "updatedAt" | "inventoryDeducted" | "orderTime">): Promise<Order | null> {
    const orderNumber = `ORD-${Date.now().toString().slice(-6)}`;
    
    // 1. Insert Order
    const { data, error } = await supabase
      .from('orders')
      .insert({
        order_number: orderNumber,
        customer_id: order.customerId,
        customer_name: order.customerName,
        customer_email: order.customerEmail,
        subtotal: order.subtotal,
        tax: order.tax,
        total: order.total,
        discount: order.discount,
        discount_type: order.discountType,
        status: order.status,
        payment_status: "unpaid",
        amount_paid: 0,
        amount_due: order.total,
        notes: order.notes,
        delivery_date: order.deliveryDate,
        order_time: order.orderTime,
        inventory_deducted: false,
        created_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) {
      console.error('Error adding order:', error);
      return null;
    }

    // 2. Insert Items
    if (order.items && order.items.length > 0) {
      const itemsToInsert = order.items.map(item => ({
        order_id: data.id,
        product_id: item.productId,
        product_name: item.productName,
        product_name_hebrew: item.productNameHebrew,
        quantity: item.quantity,
        price_per_lb: item.pricePerLb,
        total_price: item.totalPrice,
        discount: item.discount,
        discount_type: item.discountType,
        final_price: item.finalPrice
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(itemsToInsert);

      if (itemsError) {
        console.error('Error adding order items:', itemsError);
      }
    }

    return this.getOrder(data.id);
  },

  async updateOrder(order: Order): Promise<void> {
    const { error } = await supabase
      .from('orders')
      .update({
        customer_id: order.customerId,
        customer_name: order.customerName,
        customer_email: order.customerEmail,
        subtotal: order.subtotal,
        tax: order.tax,
        total: order.total,
        discount: order.discount,
        discount_type: order.discountType,
        status: order.status,
        payment_status: order.paymentStatus,
        amount_paid: order.amountPaid,
        amount_due: order.amountDue,
        notes: order.notes,
        delivery_date: order.deliveryDate,
        order_time: order.orderTime,
        inventory_deducted: order.inventoryDeducted
      })
      .eq('id', order.id);

    if (error) console.error('Error updating order:', error);

    if (order.items) {
      await supabase.from('order_items').delete().eq('order_id', order.id);
      
      if (order.items.length > 0) {
        const itemsToInsert = order.items.map(item => ({
          order_id: order.id,
          product_id: item.productId,
          product_name: item.productName,
          product_name_hebrew: item.productNameHebrew,
          quantity: item.quantity,
          price_per_lb: item.pricePerLb,
          total_price: item.totalPrice,
          discount: item.discount,
          discount_type: item.discountType,
          final_price: item.finalPrice
        }));

        await supabase.from('order_items').insert(itemsToInsert);
      }
  },

  async deleteOrder(id: string): Promise<void> {
    const { error } = await supabase.from('orders').delete().eq('id', id);
    if (error) console.error('Error deleting order:', error);
  },

  // --- Invoices ---
  async getInvoices(): Promise<Invoice[]> {
    const { data, error } = await supabase
      .from('invoices')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching invoices:', error);
      return [];
    }

    return data.map((inv: any) => ({
      id: inv.id,
      order_id: inv.order_id,
      invoice_number: inv.invoice_number,
      customer_id: inv.customer_id,
      customer_name: inv.customer_name,
      customer_email: inv.customer_email,
      items_json: inv.items_json,
      subtotal: inv.subtotal,
      tax: inv.tax,
      total: inv.total,
      paid: inv.paid,
      payment_status: inv.payment_status as "unpaid" | "partial" | "paid",
      amount_paid: inv.amount_paid,
      amount_due: inv.amount_due,
      notes: inv.notes,
      due_date: inv.due_date,
      createdAt: inv.created_at
    }));
  },

  async getInvoice(id: string): Promise<Invoice | null> {
    const { data, error } = await supabase
      .from('invoices')
      .select('*')
      .eq('id', id)
      .single();

    if (error || !data) {
      console.error('Error fetching invoice:', error);
      return null;
    }

    return {
      id: data.id,
      order_id: data.order_id,
      invoice_number: data.invoice_number,
      customer_id: data.customer_id,
      customer_name: data.customer_name,
      customer_email: data.customer_email,
      items_json: data.items_json,
      subtotal: data.subtotal,
      tax: data.tax,
      total: data.total,
      paid: data.paid,
      payment_status: data.payment_status as "unpaid" | "partial" | "paid",
      amount_paid: data.amount_paid,
      amount_due: data.amount_due,
      notes: data.notes,
      due_date: data.due_date,
      createdAt: data.created_at
    };
  },

  async createInvoiceFromOrder(order: Order): Promise<Invoice | null> {
    const invoiceNumber = `INV-${Date.now().toString().slice(-6)}`;
    
    // 1. Insert Invoice
    const { data, error } = await supabase
      .from('invoices')
      .insert({
        order_id: order.id,
        invoice_number: invoiceNumber,
        customer_id: order.customerId,
        customer_name: order.customerName,
        customer_email: order.customerEmail,
        items_json: JSON.stringify(order.items),
        subtotal: order.subtotal,
        tax: order.tax,
        total: order.total,
        paid: order.paymentStatus === 'paid',
        payment_status: order.paymentStatus,
        amount_paid: order.amountPaid,
        amount_due: order.amountDue,
        due_date: order.deliveryDate
      })
      .select()
      .single();

    if (error) {
      console.error('Error creating invoice:', error);
      return null;
    }

    return {
      id: data.id,
      order_id: data.order_id,
      invoice_number: data.invoice_number,
      customer_id: data.customer_id,
      customer_name: data.customer_name,
      customer_email: data.customer_email,
      items_json: data.items_json,
      subtotal: data.subtotal,
      tax: data.tax,
      total: data.total,
      paid: data.paid,
      payment_status: data.payment_status,
      amount_paid: data.amount_paid,
      amount_due: data.amount_due,
      notes: data.notes,
      due_date: data.due_date,
      createdAt: data.created_at
    };
  },

  // --- Payments ---
  async getPaymentsByOrder(orderId: string): Promise<Payment[]> {
    const { data, error } = await supabase
      .from('payments')
      .select('*')
      .eq('order_id', orderId)
      .order('created_at', { ascending: false });

    if (error) return [];

    return data.map((p: any) => ({
      id: p.id,
      orderId: p.order_id,
      invoiceId: p.invoice_id,
      amount: p.amount,
      paymentMethod: p.payment_method,
      paymentDate: p.payment_date,
      notes: p.notes,
      creditCardLast4: p.credit_card_last4,
      confirmed: p.confirmed,
      confirmedAt: p.confirmed_at
    }));
  },

  getAllPayments: async (): Promise<Payment[]> {
    const { data, error } = await supabase
      .from('payments')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching payments:', error);
      return [];
    }

    return data.map((p: any) => ({
      id: p.id,
      orderId: p.order_id,
      invoiceId: p.invoice_id,
      amount: p.amount,
      paymentMethod: p.payment_method,
      paymentDate: p.payment_date,
      notes: p.notes,
      creditCardLast4: p.credit_card_last4,
      confirmed: p.confirmed,
      confirmedAt: p.confirmed_at
    }));
  },

  async addPayment(payment: Omit<Payment, "id" | "createdAt">): Promise<Payment | null> {
    const { data, error } = await supabase
      .from('payments')
      .insert({
        order_id: payment.orderId,
        invoice_id: payment.invoiceId,
        amount: payment.amount,
        payment_method: payment.paymentMethod,
        payment_date: payment.paymentDate,
        notes: payment.notes,
        credit_card_last4: payment.creditCardNumber ? payment.creditCardNumber.slice(-4) : undefined,
        confirmed: payment.confirmed,
        confirmed_at: payment.confirmed ? new Date().toISOString() : null
      })
      .select()
      .single();

    if (error) {
      console.error('Error adding payment:', error);
      return null;
    }

    return {
      id: data.id,
      orderId: data.order_id,
      invoiceId: data.invoice_id,
      amount: data.amount,
      paymentMethod: data.payment_method,
      paymentDate: data.payment_date,
      notes: data.notes,
      creditCardLast4: data.credit_card_last4,
      confirmed: data.confirmed,
      confirmedAt: data.confirmed_at
    };
  },

  async updatePayment(payment: Payment): Promise<void> {
    const { error } = await supabase
      .from('payments')
      .update({
        confirmed: payment.confirmed,
        confirmed_at: payment.confirmedAt
      })
      .eq('id', payment.id);

    if (error) console.error('Error updating payment:', error);
  },

  // --- Inventory ---
  async getInventory(): Promise<InventoryEntry[]> {
    const { data, error } = await supabase
      .from('inventory_entries')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching inventory entries:', error);
      return [];
    }

    return data.map((e: any) => ({
      id: e.id,
      productId: e.product_id,
      productName: e.product_name,
      amount: e.amount,
      date: e.date,
      notes: e.notes,
      createdAt: e.created_at
    }));
  },

  async addInventoryEntry(entry: Omit<InventoryEntry, "id" | "createdAt">): Promise<InventoryEntry | null> {
    const { data, error } = await supabase
      .from('inventory_entries')
      .insert({
        product_id: entry.productId,
        product_name: entry.productName,
        amount: entry.amount,
        date: entry.date,
        notes: entry.notes,
        created_at: new Date().toISOString()
      })
      .select()
      .single();

    if (error) {
      console.error('Error adding inventory entry:', error);
      return null;
    }

    // Update product stock
    const { data: product } = await supabase
      .from('products')
      .select('current_inventory')
      .eq('id', entry.productId)
      .single();
      
    if (product) {
      const newStock = (product.current_inventory || 0) + entry.amount;
      await supabase
        .from('products')
        .update({ current_inventory: newStock })
        .eq('id', entry.productId);
    }

    return {
      id: data.id,
      productId: data.product_id,
      productName: data.product_name,
      amount: data.amount,
      date: data.date,
      notes: data.notes,
      createdAt: data.created_at
    };
  },

  // --- Settings ---
  async getSettings(): Promise<Settings> {
    const { data, error } = await supabase
      .from('settings')
      .select('*')
      .limit(1)
      .maybeSingle();

    if (error) {
      console.log('No settings found, returning defaults');
      // Return defaults if not found
      return {
        id: '',
        companyName: "Satmar Montreal Matzos",
        companyNameHebrew: "סאטמאר מונטרעאל מצות",
        email: "sales@satmarmatzosmtl.ca",
        phone: "(514) 000-0000",
        address: "Montreal, QC, Canada",
        taxRate: 0.14975,
        currency: "CAD"
      };
    }

    return {
      id: data.id,
      companyName: data.company_name,
      companyNameHebrew: data.company_name_hebrew,
      email: data.email,
      phone: data.phone,
      address: data.address,
      taxRate: data.tax_rate,
      currency: data.currency
    };
  },

  async saveSettings(settings: Settings): Promise<void> {
    // Upsert settings (assume single row)
    const { error } = await supabase
      .from('settings')
      .update({
        company_name: settings.companyName,
        company_name_hebrew: settings.companyNameHebrew,
        email: settings.email,
        phone: settings.phone,
        address: settings.address,
        tax_rate: settings.taxRate,
        currency: settings.currency
      })
      .eq('id', settings.id || 1); // Assume single row

    if (error) console.error('Error saving settings:', error);
  },

  // --- Seeding ---
  async seedInitialDataIfNeeded(): Promise<void> {
    // Check if products exist
    const { count: productCount } = await supabase.from('products').select('*', { count: 'exact', head: true });
    
    if (productCount !== null && productCount < 2) {
      console.log('Seeding products...');
      const products = [
        { name: "Rashi Matzoh", name_hebrew: "מצה רש\"י", price_per_lb: 0, category: "rashi" as const, description: "Traditional Rashi style matzoh", in_stock: true, current_inventory: 0 },
        { name: "Regular Matzoh", name_hebrew: "מצה רעגולער", price_per_lb: 0, category: "regular" as const, description: "Standard matzoh", in_stock: true, current_inventory: 0 },
        { name: "Spelt Matzoh", name_hebrew: "מצה ספעלט", price_per_lb: 0, category: "spelt" as const, description: "Made with spelt flour", in_stock: true, current_inventory: 0 },
        { name: "Whole Wheat Matzoh", name_hebrew: "מצה האל וויט", price_per_lb: 0, category: "wholewheat" as const, description: "Whole wheat matzoh", in_stock: true, current_inventory: 0 },
        { name: "Matzoh Flour", name_hebrew: "מצה מעהל", price_per_lb: 0, category: "flour" as const, description: "Fine matzoh flour", in_stock: true, current_inventory: 0 },
        { name: "Shvurim Matzoh", name_hebrew: "מצה שברים", price_per_lb: 0, category: "shvurim" as const, description: "Broken matzoh pieces", in_stock: true, current_inventory: 0 },
      ];
      await supabase.from('products').insert(products);
    }

    // Check if customers exist
    const { count: customerCount } = await supabase.from('customers').select('*', { count: 'exact', head: true });
    
    if (customerCount !== null &&customerCount < 10) {
      console.log('Seeding customers...');
      // Map INITIAL_CUSTOMERS_DATA to DB format
      const customersToInsert = INITIAL_CUSTOMERS_DATA.map(c => ({
        name: c.name,
        name_hebrew: c.nameHebrew || null,
        email: c.email || null,
        phone: c.phone || null,
        mobile: c.mobile || null,
        address: c.address || null,
        city: c.city || null,
        state: c.state || null,
        zip: c.zip || null,
        notes: c.notes || null
      }));
      
      await supabase.from('customers').insert(customersToInsert);
    }
  }
};

export default supabaseService;