ALTER TABLE customers
ADD COLUMN IF NOT EXISTS title_hebrew TEXT,
ADD COLUMN IF NOT EXISTS title_english TEXT,
ADD COLUMN IF NOT EXISTS first_name TEXT,
ADD COLUMN IF NOT EXISTS last_name TEXT,
ADD COLUMN IF NOT EXISTS first_name_hebrew TEXT,
ADD COLUMN IF NOT EXISTS last_name_hebrew TEXT,
ADD COLUMN IF NOT EXISTS house_number TEXT,
ADD COLUMN IF NOT EXISTS apt TEXT,
ADD COLUMN IF NOT EXISTS street TEXT;