// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js"; // Fixed: Added proper import statement

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export type Database = {
  // Define your database schema here
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);